# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import mysql.connector as mc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 397)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 121, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 10, 251, 136))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_2.addWidget(self.lineEdit_7)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 150, 381, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 220, 381, 131))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 360, 381, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.pushButton_3.clicked.connect(self.Insertproduct)
        self.pushButton_2.clicked.connect(self.updateproduct)
        self.pushButton_5.clicked.connect(self.deleteproduct)
        self.pushButton_4.clicked.connect(self.loadproduct)
        self.pushButton.clicked.connect(self.filterproduct)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def getByid(self, row):
        try:
            iditem = self.tableWidget.item(row,0)
            barkodeitem = self.tableWidget.item(row,1)
            nameitem = self.tableWidget.item(row,2)
            kategoriitem = self.tableWidget.item(row,3)
            qtyitem = self.tableWidget.item(row,4)
            hargaitem = self.tableWidget.item(row,5)
            if iditem :
                valueid = iditem.text()
                valuebarkode = barkodeitem.text()
                valuename = nameitem.text()
                valuekategori = kategoriitem.text()
                valueqty = qtyitem.text()
                valueharga = hargaitem.text()
                self.lineEdit_2.setText(valueid)
                self.lineEdit_3.setText(valuebarkode)
                self.lineEdit_4.setText(valuename)
                self.lineEdit_5.setText(valuekategori)
                self.lineEdit_6.setText(valueqty)
                self.lineEdit_7.setText(valueharga)
            self.label_7.setText("Data Product Berhasil Dipillih")
        except mc.Error as err:
            self.label_7.setText("Data Product Gagal Dipilih")
            
    def Insertproduct(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )   
            cursor = mydb.cursor()
            id = self.lineEdit_2.text()
            barkode = self.lineEdit_3.text()
            name = self.lineEdit_4.text()
            kategori = self.lineEdit_5.text()
            qty = self.lineEdit_6.text()
            harga = self.lineEdit_7.text()
            sql ="INSERT INTO product (id,barkode,name,kategori,qty,harga) VALUES (%s,%s,%s,%s,%s,%s)"
            val = (id,barkode,name,kategori,qty,harga)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_7.setText("Data Product Berhasil Disimpan")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")
            self.lineEdit_7.setText("")
        except mc.Error as err:
            self.label_7.setText("Data Product Gagal Disimpan")
            
    def updateproduct(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )   
            cursor = mydb.cursor()
            id = self.lineEdit_2.text()
            barkode = self.lineEdit_3.text()
            name = self.lineEdit_4.text()
            kategori = self.lineEdit_5.text()
            qty = self.lineEdit_6.text()
            harga = self.lineEdit_7.text()
            sql ="UPDATE product Set barkode = (%s), name = (%s), kategori = (%s), qty = (%s), harga = (%s)  WHERE id = (%s)"
            val = (id,barkode,name,kategori,qty,harga)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_7.setText("Data Product Berhasil DiUpdate")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")
            self.lineEdit_7.setText("")
        except mc.Error as err:
            self.label_7.setText("Data Product Gagal DiUpdate")
            
    def deleteproduct(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )
            cursor = mydb.cursor()
            id = self.lineEdit_2.text()
            sql ="DELETE FROM product WHERE id = %s"
            val = (id,)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Product Berhasil DiDelete")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")
            self.lineEdit_7.setText("")
        except mc.Error as err:
            self.label_7.setText("Data Product Gagal DiDelete") 
            
    def loadproduct(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM product ORDER BY id ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.label_7.setText("Data Product Berhasil DiTampilkan")
        except mc.Error as err:
            self.label_7.setText("Data Product Gagal DiTampilkan")
            
    def filterproduct(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_penjualan"
        )
            mycursor = mydb.cursor()
            srckat = self.lineEdit_7.text()
            sql = "SELECT * FROM product WHERE id LIKE %s OR name LIKE %s ORDER BY id ASC"
            val = (f"%{srckat}%", f"%{srckat}%")
            mycursor.execute(sql,val)
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.label_7.setText("Hasil Filter Data Kategori ")
        except mc.Error as err:
            self.label_7.setText("Filter Gagal")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID "))
        self.label_2.setText(_translate("Form", "BARKODE"))
        self.label_3.setText(_translate("Form", "NAME"))
        self.label_4.setText(_translate("Form", "KATEGORI"))
        self.label_5.setText(_translate("Form", "QTY"))
        self.label_6.setText(_translate("Form", "HARGA"))
        self.pushButton_3.setText(_translate("Form", "INSERT"))
        self.pushButton_2.setText(_translate("Form", "UPDATE"))
        self.pushButton_5.setText(_translate("Form", "DELETE"))
        self.pushButton_4.setText(_translate("Form", "LOAD DATA"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "BARKODE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "KATEGORI"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "QTY"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "HARGA"))
        self.pushButton.setText(_translate("Form", "FILTER DATA"))
        self.label_7.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
